spark.master local[*]
spark.app.name Experiment

# Packages to include (this is your "dependencies")
spark.jars.packages org.apache.hadoop:hadoop-azure:3.3.4,com.azure:azure-storage-file-datalake:12.16.0,com.azure:azure-identity:1.10.4

# Azure Storage Auth Configs
spark.hadoop.fs.azure.account.auth.type.darwinadls.dfs.core.windows.net OAuth
spark.hadoop.fs.azure.account.oauth.provider.type.darwinadls.dfs.core.windows.net org.apache.hadoop.fs.azurebfs.oauth2.BearerTokenProvider

